-- collection_presets seed
-- New presets are authored directly in Supabase Studio.
--
-- Schema reference:
--   collection_presets (
--     id            text PRIMARY KEY,          -- "urban-dusk"
--     name          jsonb,                     -- {"en":"Urban Dusk","lt":"Miesto prieblanda"}
--     designer      text,                      -- "dizaino_dialogai"
--     vibe          text,                      -- "light-and-airy" | "warm-and-grounded" | "bold-and-moody"
--     room_category text,                      -- "kitchen" | "living-room" | "bedroom" | "bathroom"
--     image_url     text,                      -- single representative photo URL
--     materials     jsonb                      -- {"floor":"solido-bolsena","bottomCabinets":"velvet-7393","worktops":"icono-arabesca-marmo"}
--   )
--
-- Slot keys for materials map to surfaces.ts:
--   floor, bottomCabinets, topCabinets, tallCabinets, shelves,
--   worktops, walls, accents, tiles, additionalTiles
