-- SM-art cabinet front materials
-- Upload WebP files to: material-images/SM-art/ in Supabase storage before running this.
-- Column order matches materials table: id, technical_code, name, role, texture,
--   lightness, warmth, pattern, texture_prompt, image_url, showroom_ids,
--   material_type, tier, description, chroma

INSERT INTO materials (id, technical_code, name, role, texture, lightness, warmth, pattern, texture_prompt, image_url, showroom_ids, material_type, tier, description, chroma) VALUES

-- ── Metallic (Met) ──────────────────────────────────────────────────────────
(gen_random_uuid(), 'sm-art-me02-acciaio-met',
 '{"en":"Acciaio","lt":"Acciaio"}',
 ARRAY['front'], 'metal', 35, 0.0, 15,
 'Dark gunmetal brushed metal surface with fine vertical striations, matte sheen.',
 'https://nimrggpqcvgpgdmcermb.supabase.co/storage/v1/object/public/material-images/SM-art/SM_art_ME02_Acciaio_Met.webp',
 ARRAY['trukme'], 'LMDP', 'optimal',
 '{"en":"Dark gunmetal brushed finish with fine vertical striations.","lt":"Tamsus metalinis šlifuotas paviršius."}',
 0),

(gen_random_uuid(), 'sm-art-me04-brunito-met',
 '{"en":"Brunito","lt":"Brunito"}',
 ARRAY['front'], 'metal', 42, 0.1, 15,
 'Warm grey-brown burnished metal with fine vertical striations, satin sheen.',
 'https://nimrggpqcvgpgdmcermb.supabase.co/storage/v1/object/public/material-images/SM-art/SM_art_ME04_Brunito_Met.webp',
 ARRAY['trukme'], 'LMDP', 'optimal',
 '{"en":"Warm grey-brown burnished metal, satin finish.","lt":"Šiltas pilkšvai rudas degintas metalas."}',
 0),

-- ── Olympus (stone-effect panels) ───────────────────────────────────────────
(gen_random_uuid(), 'sm-art-ol01-zeus-olympus',
 '{"en":"Zeus","lt":"Zeus"}',
 ARRAY['front'], 'plain', 72, -0.05, 40,
 'Light grey stone-effect panel with subtle veining and cool undertones, matte finish.',
 'https://nimrggpqcvgpgdmcermb.supabase.co/storage/v1/object/public/material-images/SM-art/SM_art_OL01_Zeus_Olympus.webp',
 ARRAY['trukme'], 'LMDP', 'optimal',
 '{"en":"Light grey stone-effect panel with subtle veining.","lt":"Šviesiai pilkas akmens efekto paviršius."}',
 0),

(gen_random_uuid(), 'sm-art-ol02-athena-olympus',
 '{"en":"Athena","lt":"Athena"}',
 ARRAY['front'], 'plain', 28, 0.1, 70,
 'Dark warm brown layered stone-effect panel with dramatic natural movement, matte finish.',
 'https://nimrggpqcvgpgdmcermb.supabase.co/storage/v1/object/public/material-images/SM-art/SM_art_OL02_Athena_Olympus.webp',
 ARRAY['trukme'], 'LMDP', 'optimal',
 '{"en":"Dark warm brown layered stone-effect with dramatic natural movement.","lt":"Tamsus šiltas rudas akmens efektas su dramatiška tekstūra."}',
 0),

(gen_random_uuid(), 'sm-art-ol04-apollo-olympus',
 '{"en":"Apollo","lt":"Apollo"}',
 ARRAY['front'], 'plain', 12, 0.0, 60,
 'Near-black dark stone-effect panel with fine white veining, matte finish.',
 'https://nimrggpqcvgpgdmcermb.supabase.co/storage/v1/object/public/material-images/SM-art/SM_art_OL04_Apollo_Olympus.webp',
 ARRAY['trukme'], 'LMDP', 'optimal',
 '{"en":"Near-black stone-effect panel with fine white veining.","lt":"Beveik juodas akmens efektas su baltomis gyslelėmis."}',
 0),

(gen_random_uuid(), 'sm-art-ol05-hera-olympus',
 '{"en":"Hera","lt":"Hera"}',
 ARRAY['front'], 'plain', 85, 0.0, 40,
 'White stone-effect panel with soft grey veining, matte finish.',
 'https://nimrggpqcvgpgdmcermb.supabase.co/storage/v1/object/public/material-images/SM-art/SM_art_OL05_Hera_Olympus.webp',
 ARRAY['trukme'], 'LMDP', 'optimal',
 '{"en":"White stone-effect panel with soft grey veining.","lt":"Baltas akmens efektas su subtiliomis pilkomis gyslelėmis."}',
 0),

(gen_random_uuid(), 'sm-art-ol07-dionysus-olympus',
 '{"en":"Dionysus","lt":"Dionysus"}',
 ARRAY['front'], 'plain', 62, 0.1, 30,
 'Warm grey terrazzo-effect panel with stone speckle, matte finish.',
 'https://nimrggpqcvgpgdmcermb.supabase.co/storage/v1/object/public/material-images/SM-art/SM_art_OL07_Dionysus_Olympus.webp',
 ARRAY['trukme'], 'LMDP', 'optimal',
 '{"en":"Warm grey terrazzo-effect with stone speckle.","lt":"Šiltas pilkas terazo efektas su akmenų įtrūkimais."}',
 0),

(gen_random_uuid(), 'sm-art-ol08-artemis-olympus',
 '{"en":"Artemis","lt":"Artemis"}',
 ARRAY['front'], 'plain', 33, 0.0, 30,
 'Dark grey terrazzo-effect panel with stone speckle, matte finish.',
 'https://nimrggpqcvgpgdmcermb.supabase.co/storage/v1/object/public/material-images/SM-art/SM_art_OL08_Artemis_Olympus.webp',
 ARRAY['trukme'], 'LMDP', 'optimal',
 '{"en":"Dark grey terrazzo-effect panel with stone speckle.","lt":"Tamsiai pilkas terazo efektas su akmenų įtrūkimais."}',
 0),

(gen_random_uuid(), 'sm-art-ol09-calacatta-olympus',
 '{"en":"Calacatta","lt":"Calacatta"}',
 ARRAY['front'], 'plain', 90, 0.1, 30,
 'Off-white Calacatta-look stone panel with warm soft veining, matte finish.',
 'https://nimrggpqcvgpgdmcermb.supabase.co/storage/v1/object/public/material-images/SM-art/SM_art_OL09_Calacatta_Olympus.webp',
 ARRAY['trukme'], 'LMDP', 'optimal',
 '{"en":"Off-white Calacatta-look panel with warm soft veining.","lt":"Šilta balta kalakatos efekto plokštė su subtiliomis gyslelėmis."}',
 0),

(gen_random_uuid(), 'sm-art-ol10-arabescato-olympus',
 '{"en":"Arabescato","lt":"Arabescato"}',
 ARRAY['front'], 'plain', 80, 0.2, 70,
 'White Arabescato marble-effect panel with dramatic warm gold and grey veining, matte finish.',
 'https://nimrggpqcvgpgdmcermb.supabase.co/storage/v1/object/public/material-images/SM-art/SM_art_OL10_Arabescato_Olympus.webp',
 ARRAY['trukme'], 'LMDP', 'optimal',
 '{"en":"White Arabescato marble-effect with dramatic warm gold and grey veining.","lt":"Baltas arabeskato efektas su dramatiška aukso ir pilkos spalvos tekstūra."}',
 0),

-- ── Malta (coloured suede-look) ──────────────────────────────────────────────
(gen_random_uuid(), 'sm-art-ma11-rabat-malta',
 '{"en":"Rabat","lt":"Rabat"}',
 ARRAY['front'], 'plain', 38, 0.4, 5,
 'Warm terracotta plain suede-look surface, matte finish.',
 'https://nimrggpqcvgpgdmcermb.supabase.co/storage/v1/object/public/material-images/SM-art/SM_art_MA11-Rabat_Malta.webp',
 ARRAY['trukme'], 'LMDP', 'optimal',
 '{"en":"Warm terracotta suede-look matte surface.","lt":"Šiltas terakotos atspalvio zomšos efekto matinis paviršius."}',
 50),

(gen_random_uuid(), 'sm-art-ma13-gozo-malta',
 '{"en":"Gozo","lt":"Gozo"}',
 ARRAY['front'], 'plain', 40, -0.3, 5,
 'Olive-sage green plain suede-look surface, matte finish.',
 'https://nimrggpqcvgpgdmcermb.supabase.co/storage/v1/object/public/material-images/SM-art/SM_art_MA13-Gozo_Malta.webp',
 ARRAY['trukme'], 'LMDP', 'optimal',
 '{"en":"Olive-sage green suede-look matte surface.","lt":"Alyvuogių-šalavijų žalios spalvos zomšos efekto matinis paviršius."}',
 45),

(gen_random_uuid(), 'sm-art-ma15-sliema-malta',
 '{"en":"Sliema","lt":"Sliema"}',
 ARRAY['front'], 'plain', 62, 0.3, 5,
 'Dusty rose plain suede-look surface, matte finish.',
 'https://nimrggpqcvgpgdmcermb.supabase.co/storage/v1/object/public/material-images/SM-art/SM_art_MA15-Sliema_Malta.webp',
 ARRAY['trukme'], 'LMDP', 'optimal',
 '{"en":"Dusty rose suede-look matte surface.","lt":"Dulksvai rožinės spalvos zomšos efekto matinis paviršius."}',
 35),

-- ── Intagli (wood veneer) ────────────────────────────────────────────────────
(gen_random_uuid(), 'sm-art-in04-cannella-intagli',
 '{"en":"Cannella","lt":"Cannella"}',
 ARRAY['front'], 'wood', 48, 0.25, 28,
 'Medium warm cinnamon-brown wood veneer with fine vertical grain, matte finish.',
 'https://nimrggpqcvgpgdmcermb.supabase.co/storage/v1/object/public/material-images/SM-art/SM_art_IN04_Cannella_Intagli.webp',
 ARRAY['trukme'], 'LMDP', 'optimal',
 '{"en":"Medium warm cinnamon-brown wood veneer, fine vertical grain.","lt":"Vidutinio atspalvio šilto cinamono medienos faneravimas."}',
 0),

(gen_random_uuid(), 'sm-art-in05-cumino-intagli',
 '{"en":"Cumino","lt":"Cumino"}',
 ARRAY['front'], 'wood', 38, 0.2, 28,
 'Medium-dark warm brown wood veneer with fine vertical grain, matte finish.',
 'https://nimrggpqcvgpgdmcermb.supabase.co/storage/v1/object/public/material-images/SM-art/SM_art_IN05_Cumino_Intagli.webp',
 ARRAY['trukme'], 'LMDP', 'optimal',
 '{"en":"Medium-dark warm brown wood veneer, fine vertical grain.","lt":"Tamsesnio atspalvio šiltas rudas medienos faneravimas."}',
 0),

(gen_random_uuid(), 'sm-art-in07-pepe-intagli',
 '{"en":"Pepe","lt":"Pepe"}',
 ARRAY['front'], 'wood', 10, 0.05, 25,
 'Near-black dark wood veneer with fine vertical grain, matte finish.',
 'https://nimrggpqcvgpgdmcermb.supabase.co/storage/v1/object/public/material-images/SM-art/SM_art_IN07_Pepe_Intagli.webp',
 ARRAY['trukme'], 'LMDP', 'optimal',
 '{"en":"Near-black dark wood veneer, fine vertical grain.","lt":"Beveik juodas tamsus medienos faneravimas su smulkiu grūdėliu."}',
 0),

-- ── Atom (solid colour) ──────────────────────────────────────────────────────
(gen_random_uuid(), 'sm-art-0041-atmosfera-atom',
 '{"en":"Atmosfera","lt":"Atmosfera"}',
 ARRAY['front'], 'plain', 72, -0.1, 5,
 'Light sage-mint flat matte colour, smooth surface.',
 'https://nimrggpqcvgpgdmcermb.supabase.co/storage/v1/object/public/material-images/SM-art/SM_art_0041_Atmosfera_Atom.webp',
 ARRAY['trukme'], 'LMDP', 'optimal',
 '{"en":"Light sage-mint flat matte colour.","lt":"Šviesiai mėtų žalios spalvos matinis paviršius."}',
 25),

(gen_random_uuid(), 'sm-art-0042-sottobosco-atom',
 '{"en":"Sottobosco","lt":"Sottobosco"}',
 ARRAY['front'], 'plain', 58, -0.1, 5,
 'Medium sage-green flat matte colour, smooth surface.',
 'https://nimrggpqcvgpgdmcermb.supabase.co/storage/v1/object/public/material-images/SM-art/SM_art_0042_Sottobosco_Atom.webp',
 ARRAY['trukme'], 'LMDP', 'optimal',
 '{"en":"Medium sage-green flat matte colour.","lt":"Vidutinio atspalvio šalavijų žalios spalvos matinis paviršius."}',
 30),

-- ── Dune (structured textured panels) ───────────────────────────────────────
(gen_random_uuid(), 'sm-art-d003-atacama-dune',
 '{"en":"Atacama","lt":"Atacama"}',
 ARRAY['front'], 'plain', 65, 0.3, 45,
 'Warm sandy beige panel with fine vertical rope-like texture, matte finish.',
 'https://nimrggpqcvgpgdmcermb.supabase.co/storage/v1/object/public/material-images/SM-art/SM_art_D003_Atacama_Dune.webp',
 ARRAY['trukme'], 'LMDP', 'optimal',
 '{"en":"Warm sandy beige with fine vertical rope-like texture.","lt":"Šiltas smėlio bežo atspalvis su subtilia vertikalia virvės tekstūra."}',
 0),

(gen_random_uuid(), 'sm-art-d006-betonmarsiglia-dune',
 '{"en":"Beton Marsiglia","lt":"Beton Marsiglia"}',
 ARRAY['front'], 'plain', 68, -0.1, 40,
 'Cool grey panel with fine vertical ribbed texture, concrete-like matte finish.',
 'https://nimrggpqcvgpgdmcermb.supabase.co/storage/v1/object/public/material-images/SM-art/SM_art_D006_BetonMarsiglia_Dune.webp',
 ARRAY['trukme'], 'LMDP', 'optimal',
 '{"en":"Cool grey with fine vertical ribbed texture, concrete-like.","lt":"Vėsiai pilkas paviršius su subtilia vertikalia rievėta tekstūra."}',
 0),

-- ── Rio (rough stone surface) ────────────────────────────────────────────────
(gen_random_uuid(), 'sm-art-r006-bravo-rio',
 '{"en":"Bravo","lt":"Bravo"}',
 ARRAY['front'], 'plain', 72, 0.1, 15,
 'Light warm beige rough stone-texture panel, matte finish.',
 'https://nimrggpqcvgpgdmcermb.supabase.co/storage/v1/object/public/material-images/SM-art/SM_art_R006_Bravo_Rio.webp',
 ARRAY['trukme'], 'LMDP', 'optimal',
 '{"en":"Light warm beige rough stone texture.","lt":"Šiltas šviesos bežo gruoblėto akmens paviršius."}',
 0),

(gen_random_uuid(), 'sm-art-r007-delaplata-rio',
 '{"en":"De La Plata","lt":"De La Plata"}',
 ARRAY['front'], 'plain', 68, -0.05, 10,
 'Light cool grey rough stone-texture panel, matte finish.',
 'https://nimrggpqcvgpgdmcermb.supabase.co/storage/v1/object/public/material-images/SM-art/SM_art_R007_DeLaPlata_Rio.webp',
 ARRAY['trukme'], 'LMDP', 'optimal',
 '{"en":"Light cool grey rough stone texture.","lt":"Vėsiai pilkas gruoblėto akmens paviršius."}',
 0),

-- ── Reverso / Polvere (woven & sparkle) ─────────────────────────────────────
(gen_random_uuid(), 'sm-art-re02-meriggio-reverso',
 '{"en":"Meriggio","lt":"Meriggio"}',
 ARRAY['front'], 'plain', 55, 0.35, 50,
 'Warm golden-tan woven basket-weave texture panel, matte finish.',
 'https://nimrggpqcvgpgdmcermb.supabase.co/storage/v1/object/public/material-images/SM-art/SM_art_RE02_Meriggio_Reverso.webp',
 ARRAY['trukme'], 'LMDP', 'optimal',
 '{"en":"Warm golden-tan woven basket-weave texture.","lt":"Šiltas auksiniai rusvos spalvos pintas paviršius."}',
 0),

(gen_random_uuid(), 'sm-art-re05-notte-reverso',
 '{"en":"Notte","lt":"Notte"}',
 ARRAY['front'], 'plain', 18, 0.1, 50,
 'Very dark warm brown woven basket-weave texture panel, matte finish.',
 'https://nimrggpqcvgpgdmcermb.supabase.co/storage/v1/object/public/material-images/SM-art/SM_art_RE05_Notte_Reverso.webp',
 ARRAY['trukme'], 'LMDP', 'optimal',
 '{"en":"Very dark warm brown woven basket-weave texture.","lt":"Labai tamsus šiltas rudas pintas paviršius."}',
 0),

(gen_random_uuid(), 'sm-art-re09-scintilla-polvere',
 '{"en":"Scintilla Polvere","lt":"Scintilla Polvere"}',
 ARRAY['front'], 'plain', 42, 0.4, 10,
 'Warm terracotta-rust plain panel with fine metallic sparkle, matte finish.',
 'https://nimrggpqcvgpgdmcermb.supabase.co/storage/v1/object/public/material-images/SM-art/SM_art_RE09_Scintilla_Polvere.webp',
 ARRAY['trukme'], 'LMDP', 'optimal',
 '{"en":"Warm terracotta-rust with fine metallic sparkle.","lt":"Šiltas terakotos-rūdžių atspalvis su subtiliu metaliniu blizgesiu."}',
 55),

(gen_random_uuid(), 'sm-art-re09-scintilla-reverso',
 '{"en":"Scintilla Reverso","lt":"Scintilla Reverso"}',
 ARRAY['front'], 'plain', 22, 0.15, 50,
 'Dark warm brown woven basket-weave texture panel, matte finish.',
 'https://nimrggpqcvgpgdmcermb.supabase.co/storage/v1/object/public/material-images/SM-art/SM_art_RE09_Scintilla_Reverso.webp',
 ARRAY['trukme'], 'LMDP', 'optimal',
 '{"en":"Dark warm brown woven basket-weave texture.","lt":"Tamsus šiltas rudas pintas paviršius."}',
 0),

(gen_random_uuid(), 'sm-art-re10-riflesso-polvere',
 '{"en":"Riflesso","lt":"Riflesso"}',
 ARRAY['front'], 'plain', 40, 0.1, 10,
 'Dark warm taupe-grey plain panel with fine metallic sparkle, matte finish.',
 'https://nimrggpqcvgpgdmcermb.supabase.co/storage/v1/object/public/material-images/SM-art/SM_art_RE10_Riflesso_Polvere.webp',
 ARRAY['trukme'], 'LMDP', 'optimal',
 '{"en":"Dark warm taupe-grey with fine metallic sparkle.","lt":"Tamsus šiltas taupinės pilkos spalvos paviršius su metaliniu blizgesiu."}',
 0),

(gen_random_uuid(), 'sm-art-re11-penombra-polvere',
 '{"en":"Penombra Polvere","lt":"Penombra Polvere"}',
 ARRAY['front'], 'plain', 20, 0.0, 10,
 'Near-black charcoal plain panel with fine metallic sparkle, matte finish.',
 'https://nimrggpqcvgpgdmcermb.supabase.co/storage/v1/object/public/material-images/SM-art/SM_art_RE11_Penombra_Polvere.webp',
 ARRAY['trukme'], 'LMDP', 'optimal',
 '{"en":"Near-black charcoal with fine metallic sparkle.","lt":"Beveik juodas anglies atspalvis su metaliniu blizgesiu."}',
 0),

(gen_random_uuid(), 'sm-art-re11-penombra-reverso',
 '{"en":"Penombra Reverso","lt":"Penombra Reverso"}',
 ARRAY['front'], 'plain', 12, 0.0, 50,
 'Near-black woven basket-weave texture panel, matte finish.',
 'https://nimrggpqcvgpgdmcermb.supabase.co/storage/v1/object/public/material-images/SM-art/SM_art_RE11_Penombra_Reverso.webp',
 ARRAY['trukme'], 'LMDP', 'optimal',
 '{"en":"Near-black woven basket-weave texture.","lt":"Beveik juodas pintas paviršius."}',
 0),

-- ── Trama (fabric/textile) ───────────────────────────────────────────────────
(gen_random_uuid(), 'sm-art-t001-mohair-trama',
 '{"en":"Mohair","lt":"Mohair"}',
 ARRAY['front'], 'plain', 90, 0.1, 20,
 'Off-white fabric-look panel with subtle woven linen texture, matte finish.',
 'https://nimrggpqcvgpgdmcermb.supabase.co/storage/v1/object/public/material-images/SM-art/SM_art_T001_Mohair_Trama.webp',
 ARRAY['trukme'], 'LMDP', 'optimal',
 '{"en":"Off-white fabric-look panel with subtle woven linen texture.","lt":"Šilta balta audinį primenantis paviršius su subtilia lino tekstūra."}',
 0);
